from django.urls import path
from dashboard.views import login_view,login_api,developer_page,dashboard,bottler,developer_page_posm,CoolerDefaultAPIView,PosmDefaultAPIView,edit_developer_cooler_api,edit_developer_posm_api,get_rsms_gms_by_bottler,get_gms_by_bottler,edit_cooler_api,sales_data_date,get_rsms_by_bottler,get_restaurants_by_bottler,get_rsms_by_gm,get_restaurants_by_gm,get_restaurants_by_rsm,get_restaurant_target,get_cooler,get_posm,edit_posm_api,edit_crate_target_api,edit_restaurant_target_api,details_gm,details_rsm,compliance_data_date,consumer_data_date,edit_rsm_api,edit_gm_api,delete_rsm_api,delete_gm_api,restaurant,create_restaurant_api,get_crate_target,create_restaurant_target_api,delete_restaurant_api,details_restaurant,download_template,upload_crate_sales,lucky_draw,done_draws,report,generate_report,export_report_excel,api_logout
app_name = "dashboard"

urlpatterns = [
# urls.py

    path('login/', login_view, name="login"),          
    path('api/login/', login_api, name="login_api"),
    path('developer-page/',developer_page,name="developer-page"),
    path('developer-page-posm/',developer_page_posm,name="developer-page-posm"),
    path('index/',dashboard,name="index"),
    path('bottler/',bottler,name="bottler"),
    path('detail-gm/<int:gm_id>/',details_gm,name="detail-gm"),
    path('detail-rsm/<int:rsm_id>/',details_rsm,name="detail-rsm"),
    path('api/edit_rsm_api/<int:rsm_id>/',edit_rsm_api,name="edit_rsm_api"),
    path('api/edit_gm_api/<int:gm_id>/',edit_gm_api,name="edit_gm_api"),
    path("api/delete_rsm_api/<int:rsm_id>/", delete_rsm_api, name="delete_rsm_api"),
    path("api/delete_gm_api/<int:gm_id>/", delete_gm_api, name="delete_gm_api"),
    path('restaurant/',restaurant,name="restaurant"),
    path("api/create-restaurant/", create_restaurant_api, name="create-restaurant-api"),
    path("api/create-restaurant-target/", create_restaurant_target_api, name="create-restaurant-target-api"),
    # path("api/edit-restaurant/<int:restaurant_id>/", edit_restaurant_api, name="edit-restaurant-api"),
    path("api/delete-restaurant/<int:restaurant_id>/", delete_restaurant_api, name="delete-restaurant-api"),
    path('details-restaurant/<int:restaurant_id>/',details_restaurant,name="details-restaurant"),
    path('api/get-restaurant-target/<int:target_id>/',get_restaurant_target,name="get_restaurant_target"),
    path('api/get-crate-target/<int:crate_id>/',get_crate_target,name="get_restaurant_target"),    
    path('api/restaurant-targets/<int:target_id>/edit/',edit_restaurant_target_api,name="edit_restaurant_target_api"),
    path('api/crate-targets/<int:crate_id>/edit/',edit_crate_target_api,name="edit_crate_target_api"),
    path('api/cooler/default/', CoolerDefaultAPIView.as_view(), name='cooler-default'),
    path('api/posm/default/', PosmDefaultAPIView.as_view(), name='posm-default'),
    path('api/get-cooler/<int:cooler_id>/',get_cooler,name="get_cooler"),
    path('api/cooler-update/<int:cooler_id>/',edit_cooler_api,name="edit_cooler_api"),
    path('api/get-posm/<int:posm_id>/',get_posm,name="get_posm"),
    path('api/posm-update/<int:posm_id>/',edit_posm_api,name="edit_posm_api"),
    path('api/developer-cooler-update/<int:cooler_id>/',edit_developer_cooler_api,name="editdeveloper__cooler_api"),
    path('api/developer-posm-update/<int:posm_id>/',edit_developer_posm_api,name="editdeveloper__posm_api"),
    path("api/get-rsms-gms/<int:bottler_id>/", get_rsms_gms_by_bottler, name="get_rsms_gms"),
    path("api/gms/<int:bottler_id>/", get_gms_by_bottler, name="get_gms_by_bottler"),
    path("api/rsms/<int:bottler_id>/", get_rsms_by_bottler, name="get_rsms_by_bottler"),
    path("api/restaurants/<int:bottler_id>/", get_restaurants_by_bottler, name="get_restaurants_by_bottler"),
    path("api/rsms/gm/<int:gm_id>/", get_rsms_by_gm, name="get_rsms_by_gm"),
    path("api/restaurants/gm/<int:gm_id>/", get_restaurants_by_gm, name="get_restaurants_by_gm"),
    path("api/restaurants/rsm/<int:rsm_id>/", get_restaurants_by_rsm, name="get_restaurants_by_rsm"),
    path("sales-data/", sales_data_date, name="sales_data_date"),
    path("compliance-data/", compliance_data_date, name="compliance_data_date"),
    path('consumer-data/',consumer_data_date,name="consumer_data_date"),
    path('lucky-draw/',lucky_draw,name="lucky-draw"),
    path('done-draws/',done_draws,name="done-draws"),
    path('report/',report,name="report"),
    path('api/generate-report/', generate_report, name='generate-report'),
    path('api/export-report-excel/', export_report_excel, name='export-report-excel'),
    path('api/download-template/', download_template, name='download-template'),
    path('api/upload-crate-sales/', upload_crate_sales, name='upload-crate-sales'),
    path('api/logout/', api_logout, name='api-logout'),
]
