# Generated by Django 5.2.5 on 2025-09-04 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_code', models.CharField(max_length=50, unique=True)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_owner_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('restaurant_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sdp_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('segment_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('route_code', models.CharField(blank=True, max_length=50, null=True)),
                ('route_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('lrb_volume', models.FloatField(default=0.0)),
                ('csd_volume', models.FloatField(default=0.0)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
