# Generated by Django 5.2.5 on 2025-09-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
