# Generated by Django 5.2.5 on 2025-09-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottler_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gm_name', models.CharField(max_length=255)),
                ('gm_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_target', models.CharField(max_length=255)),
                ('bottler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gms', to='dashboard.bottler')),
            ],
        ),
        migrations.CreateModel(
            name='RSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsm_name', models.CharField(max_length=255)),
                ('rsm_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_target', models.CharField(max_length=255)),
                ('bottler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsm', to='dashboard.bottler')),
            ],
        ),
    ]
