# Generated by Django 5.2.5 on 2025-09-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bottler_restaurant_manager_phone_number_gm_rsm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
