# Generated by Django 5.2.5 on 2025-09-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_restaurant'),
        ('restaurant', '0002_restaurant_cooler_restaurant_crate_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gm',
            name='sales_target',
        ),
        migrations.RemoveField(
            model_name='rsm',
            name='sales_target',
        ),
        migrations.AddField(
            model_name='gm',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='gms', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='gm',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsm',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='rsms', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='rsm',
            name='tagged_gms',
            field=models.ManyToManyField(blank=True, related_name='rsms', to='dashboard.gm'),
        ),
        migrations.AddField(
            model_name='rsm',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsm_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
