# Generated by Django 5.2.5 on 2025-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_gm_sales_target_remove_rsm_sales_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gm',
            name='gm_phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsm',
            name='rsm_phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
