# Generated by Django 5.2.5 on 2025-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_gm_gm_phone_number_alter_rsm_rsm_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gm',
            name='gm_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rsm',
            name='rsm_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
