# Generated by Django 5.2.5 on 2025-09-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_gm_gm_phone_number_alter_rsm_rsm_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gm',
            old_name='restaurants',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='rsm',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
