# Generated by Django 5.2.5 on 2025-09-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_restaurants_gm_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gm',
            old_name='restaurant',
            new_name='restaurants',
        ),
        migrations.RenameField(
            model_name='rsm',
            old_name='restaurant',
            new_name='restaurants',
        ),
    ]
