# Generated by Django 5.2.5 on 2025-09-05 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_cooler_restaurant_crate_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bottler',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
