# Generated by Django 5.2.5 on 2025-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_bottler_restaurant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bottler_admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visi_cooler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_cooler',
            name='visible_collers',
            field=models.IntegerField(default=0),
        ),
    ]
