# Generated by Django 5.2.5 on 2025-09-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_bottler_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='csd_volume',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lrb_volume',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='visi_cooler',
        ),
    ]
