# Generated by Django 5.2.5 on 2025-09-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_csd_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Branding_POSM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cooler_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
