# Generated by Django 5.2.5 on 2025-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_manager_remove_restaurant_manager_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_crate_sales',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
