# Generated by Django 5.2.5 on 2025-09-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_crate_sales_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_crate_sales',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
