# Generated by Django 5.2.5 on 2025-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_crate_sales_is_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_cooler',
            name='visible_collers',
        ),
        migrations.AddField(
            model_name='restaurant_cooler',
            name='raw_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_posm',
            name='raw_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
