# Generated by Django 5.2.5 on 2025-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_restaurant_cooler_visible_collers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_cooler',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant_posm',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
