# Generated by Django 5.2.5 on 2025-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurant_cooler_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_qr',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
