# Generated by Django 5.2.5 on 2025-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurant_restaurant_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='posm_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_cooler',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_posm',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
