# Generated by Django 5.2.5 on 2025-09-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_restaurant_gm_restaurants_and_more'),
        ('restaurant', '0013_restaurant_posm_type_alter_restaurant_cooler_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='bottler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='dashboard.bottler'),
        ),
    ]
