# Generated by Django 5.2.5 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_restaurant_crate_sales_saleweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_qr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_cooler',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_posm',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
