# Generated by Django 5.2.5 on 2025-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_restaurant_restaurant_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_cooler',
            name='is_manually',
            field=models.BooleanField(default=False),
        ),
    ]
