# Generated by Django 5.2.5 on 2025-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_restaurant_cooler_is_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_cooler',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
