# Generated by Django 5.2.5 on 2025-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_restaurant_cooler_is_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
