# Generated by Django 5.2.5 on 2025-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_coolersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant_posm',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant_posm',
            name='is_manually',
            field=models.BooleanField(default=False),
        ),
    ]
