# Generated by Django 5.2.5 on 2025-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='reciept_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
