# Generated by Django 5.2.5 on 2025-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumer_is_checked_consumer_reciept_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
    ]
