# Generated by Django 5.2.5 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_alter_consumer_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='reciept_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
