# Generated by Django 5.2.5 on 2025-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_alter_consumer_reciept_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='isTermsandpolicy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='isadvertisement',
            field=models.BooleanField(default=False),
        ),
    ]
