# Generated by Django 5.2.5 on 2025-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_consumer_istermsandpolicy_consumer_isadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
